VCI Client ios library in swift with an swift example aaplication
mosip/inji-vci-client-ios-swift pull request #2
Opened 2024-05-20 06:55 UTC by PoojaBabusing

2024-05-21 09:13 UTC, swatigoel requested changes

2024-05-21 09:13 UTC, swatigoel commented on Sources/VCIClient/VCIClient.swift
> +    private func handle(error: Error, logTag: String) throws {
This function is for handling error, so better to name as `handleError`

2024-05-21 09:23 UTC, swatigoel requested changes

2024-05-21 09:23 UTC, swatigoel commented on Sources/VCIClient/VCIClient.swift
> +    public func getCredential(
keep function name consistent across all platform. Please check with kotlin, it's `requestCredential`

2024-05-22 11:40 UTC, PoojaBabusing commented
Opening a new PR with the required changes and Closing this PR

2024-05-22 11:40 UTC, closed without merging